TEAM_NAME_TO_ALIAS = {
    "Arizona Cardinals": "ARI",
    "Atlanta Falcons": "ATL",
    "Baltimore Ravens": "BAL",
    "Buffalo Bills": "BUF",
    "Carolina Panthers": "CAR",
    "Chicago Bears": "CHI",
    "Cincinnati Bengals": "CIN",
    "Cleveland Browns": "CLE",
    "Dallas Cowboys": "DAL",
    "Denver Broncos": "DEN",
    "Detroit Lions": "DET",
    "Green Bay Packers": "GB",
    "Houston Texans": "HOU",
    "Indianapolis Colts": "IND",
    "Jacksonville Jaguars": "JAC",
    "Kansas City Chiefs": "KC",
    "Las Vegas Raiders": "LV",
    "Los Angeles Chargers": "LAC",
    "Los Angeles Rams": "LAR",
    "Miami Dolphins": "MIA",
    "Minnesota Vikings": "MIN",
    "New England Patriots": "NE",
    "New Orleans Saints": "NO",
    "New York Giants": "NYG",
    "New York Jets": "NYJ",
    "Philadelphia Eagles": "PHI",
    "Pittsburgh Steelers": "PIT",
    "San Francisco 49ers": "SF",
    "Seattle Seahawks": "SEA",
    "Tampa Bay Buccaneers": "TB",
    "Tennessee Titans": "TEN",
    "Washington Commanders": "WAS",
    "Washington Football Team": "WAS"
}

ALIAS_TO_PFR_CODE = {
    "ARI": "crd",
    "ATL": "atl",
    "BAL": "rav",
    "BUF": "buf",
    "CAR": "car",
    "CHI": "chi",
    "CIN": "cin",
    "CLE": "cle",
    "DAL": "dal",
    "DEN": "den",
    "DET": "det",
    "GB":  "gnb",
    "HOU": "htx",
    "IND": "clt",
    "JAC": "jax",
    "KC":  "kan",
    "LV":  "rai",
    "LAC": "sdg",
    "LAR": "ram",
    "MIA": "mia",
    "MIN": "min",
    "NE":  "nwe",
    "NO":  "nor",
    "NYG": "nyg",
    "NYJ": "nyj",
    "PHI": "phi",
    "PIT": "pit",
    "SF":  "sfo",
    "SEA": "sea",
    "TB":  "tam",
    "TEN": "oti",
    "WAS": "was",
}

TEAM_CODE_TO_ALIAS = {
    "ARI": "ARI",
    "ATL": "ATL",
    "BAL": "BAL",
    "BUF": "BUF",
    "CAR": "CAR",
    "CHI": "CHI",
    "CIN": "CIN",
    "CLE": "CLE",
    "DAL": "DAL",
    "DEN": "DEN",
    "DET": "DET",
    "GNB":  "GB",
    "HOU": "HOU",
    "IND": "IND",
    "JAX": "JAC",
    "KAN":  "KC",
    "LVR":  "LV",
    "LAC": "LAC",
    "LAR": "LAR",
    "MIA": "MIA",
    "MIN": "MIN",
    "NWE":  "NE",
    "NOR":  "NO",
    "NYG": "NYG",
    "NYJ": "NYJ",
    "PHI": "PHI",
    "PIT": "PIT",
    "SFO":  "SF",
    "SEA": "SEA",
    "TAM":  "TB",
    "TEN": "TEN",
    "WAS": "WAS",
}

def get_alias_from_tc(team_code: str) -> str:
    return TEAM_CODE_TO_ALIAS.get(team_code, "UNK")

def get_alias(team_name: str) -> str:
    return TEAM_NAME_TO_ALIAS.get(team_name, "UNK")

def get_pfr_code(alias: str) -> str:
    return ALIAS_TO_PFR_CODE.get(alias, "UNK")